#!/bin/bash

#   $$\               $$\   $$\           $$\        $$$$$$\              $$\     
#   $$ |              $$ |  $$ |          $$ |      $$$ __$$\             $$ |    
# $$$$$$\    $$$$$$\  $$ |  $$ | $$$$$$\  $$$$$$$\  $$$$\ $$ | $$$$$$$\ $$$$$$\   
# \_$$  _|  $$  __$$\ $$$$$$$$ |$$  __$$\ $$  __$$\ $$\$$\$$ |$$  _____|\_$$  _|  
#   $$ |    $$$$$$$$ |\_____$$ |$$ /  $$ |$$ |  $$ |$$ \$$$$ |\$$$$$$\    $$ |    
#   $$ |$$\ $$   ____|      $$ |$$ |  $$ |$$ |  $$ |$$ |\$$$ | \____$$\   $$ |$$\ 
#   \$$$$  |\$$$$$$$\       $$ |\$$$$$$$ |$$ |  $$ |\$$$$$$  /$$$$$$$  |  \$$$$  |
#    \____/  \_______|      \__| \____$$ |\__|  \__| \______/ \_______/    \____/ 
#                               $$\   $$ |                                        
#                               \$$$$$$  |                                        
#                                \______/                                         


# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

plugins=(git sudo zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#TE1ch0st logo in start
~/.te4gh0st/te4gh0st.py
